---
#
# Ansible managed
#
repository:
  description: Install and configure tomcat on your system.
  homepage: https://buluma.github.io/
  topics: tomcat, ansible, molecule, tox, playbook, hacktoberfest
