---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no
  vars:
    _service_test_command:
      default: /usr/bin/sleep
      Alpine: /bin/sleep
      Debian: /bin/sleep
      Ubuntu-16: /bin/sleep
      Ubuntu-18: /bin/sleep
    service_test_command: "{{ _service_test_command[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_service_test_command[ansible_os_family] | default(_service_test_command['default'])) }}"  # noqa 204 Just long.

  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.java
    - role: buluma.service
      service_list:
        - name: tomcat
          description: Tomcat application server
          start_command: "{{ service_test_command }} 3600"
          state: started
          enabled: yes
          type: forking
          restart_mode: "always"
        - name: tomcat
          description: Tomcat application server
          start_command: "{{ service_test_command }} 3601"
          state: stopped
          enabled: no
          type: forking
          restart_mode: "always"
